name: Node CI

on: [push]

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [10.x, 12.x, 13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup yarn
        run: npm i -g yarn

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

        env:
          CI: true
      - name: Codecov
        if: matrix.os === 'ubuntu-latest' && contains(matrix.os, '13')
        uses: codecov/codecov-action@v1.0.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
