name: Node CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [10.x, 12.x, 13.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Yarn install, build, test
        uses: KingScooty/actions-yarn-cy@1.0.0
        with:
          cmd: install
      - uses: uses: KingScooty/actions-yarn-cy@1.0.0
        with:
          cmd: build
      - uses: uses: KingScooty/actions-yarn-cy@1.0.0
        with:
          cmd: test
        env:
          CI: true
      - name: Codecov
        uses: codecov/codecov-action@v1.0.4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}